// Copyright 2025, Command Line Inc.
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"bytes"
	"fmt"
	"os"
	"reflect"
	"sort"
	"strings"

	"github.com/dfbb/doraterm/pkg/service"
	"github.com/dfbb/doraterm/pkg/tsgen"
	"github.com/dfbb/doraterm/pkg/util/utilfn"
	"github.com/dfbb/doraterm/pkg/dshrpc"
)

func generateTypesFile(tsTypesMap map[reflect.Type]string) error {
	fileName := "frontend/types/gotypes.d.ts"
	fmt.Fprintf(os.Stderr, "generating types file to %s\n", fileName)
	tsgen.GenerateDoraObjTypes(tsTypesMap)
	tsgen.GenerateDoraEventTypes(tsTypesMap)
	err := tsgen.GenerateServiceTypes(tsTypesMap)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating service types: %v\n", err)
		os.Exit(1)
	}
	err = tsgen.GenerateDshServerTypes(tsTypesMap)
	if err != nil {
		return fmt.Errorf("error generating dsh server types: %w", err)
	}
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Copyright 2026, Command Line Inc.\n")
	fmt.Fprintf(&buf, "// SPDX-License-Identifier: Apache-2.0\n\n")
	fmt.Fprintf(&buf, "// generated by cmd/generate/main-generatets.go\n\n")
	fmt.Fprintf(&buf, "declare global {\n\n")
	var keys []reflect.Type
	for key := range tsTypesMap {
		keys = append(keys, key)
	}
	sort.Slice(keys, func(i, j int) bool {
		iname, _ := tsgen.TypeToTSType(keys[i], tsTypesMap)
		jname, _ := tsgen.TypeToTSType(keys[j], tsTypesMap)
		return iname < jname
	})
	for _, key := range keys {
		// don't output generic types
		if strings.Contains(key.Name(), "[") {
			continue
		}
		tsCode := tsTypesMap[key]
		istr := utilfn.IndentString("    ", tsCode)
		fmt.Fprint(&buf, istr)
	}
	fmt.Fprintf(&buf, "}\n\n")
	fmt.Fprintf(&buf, "export {}\n")
	written, err := utilfn.WriteFileIfDifferent(fileName, buf.Bytes())
	if !written {
		fmt.Fprintf(os.Stderr, "no changes to %s\n", fileName)
	}
	return err
}

func generateDoraEventFile(tsTypesMap map[reflect.Type]string) error {
	fileName := "frontend/types/doraevent.d.ts"
	fmt.Fprintf(os.Stderr, "generating doraevent file to %s\n", fileName)
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Copyright 2026, Command Line Inc.\n")
	fmt.Fprintf(&buf, "// SPDX-License-Identifier: Apache-2.0\n\n")
	fmt.Fprintf(&buf, "// generated by cmd/generate/main-generatets.go\n\n")
	fmt.Fprintf(&buf, "declare global {\n\n")
	fmt.Fprint(&buf, utilfn.IndentString("    ", tsgen.GenerateDoraEventTypes(tsTypesMap)))
	fmt.Fprintf(&buf, "}\n\n")
	fmt.Fprintf(&buf, "export {}\n")
	written, err := utilfn.WriteFileIfDifferent(fileName, buf.Bytes())
	if !written {
		fmt.Fprintf(os.Stderr, "no changes to %s\n", fileName)
	}
	return err
}

func generateServicesFile(tsTypesMap map[reflect.Type]string) error {
	fileName := "frontend/app/store/services.ts"
	var buf bytes.Buffer
	fmt.Fprintf(os.Stderr, "generating services file to %s\n", fileName)
	fmt.Fprintf(&buf, "// Copyright 2026, Command Line Inc.\n")
	fmt.Fprintf(&buf, "// SPDX-License-Identifier: Apache-2.0\n\n")
	fmt.Fprintf(&buf, "// generated by cmd/generate/main-generatets.go\n\n")
	fmt.Fprintf(&buf, "import * as WOS from \"./wos\";\n")
	fmt.Fprintf(&buf, "import type { DoraEnv } from \"@/app/doraenv/doraenv\";\n\n")
	fmt.Fprintf(&buf, "function callBackendService(doraEnv: DoraEnv, service: string, method: string, args: any[], noUIContext?: boolean): Promise<any> {\n")
	fmt.Fprintf(&buf, "    if (doraEnv != null) {\n")
	fmt.Fprintf(&buf, "        return doraEnv.callBackendService(service, method, args, noUIContext)\n")
	fmt.Fprintf(&buf, "    }\n")
	fmt.Fprintf(&buf, "    return WOS.callBackendService(service, method, args, noUIContext);\n")
	fmt.Fprintf(&buf, "}\n\n")
	orderedKeys := utilfn.GetOrderedMapKeys(service.ServiceMap)
	for _, serviceName := range orderedKeys {
		serviceObj := service.ServiceMap[serviceName]
		svcStr := tsgen.GenerateServiceClass(serviceName, serviceObj, tsTypesMap)
		fmt.Fprint(&buf, svcStr)
		fmt.Fprint(&buf, "\n")
	}
	fmt.Fprintf(&buf, "export const AllServiceTypes = {\n")
	for _, serviceName := range orderedKeys {
		serviceObj := service.ServiceMap[serviceName]
		serviceType := reflect.TypeOf(serviceObj)
		tsServiceName := serviceType.Elem().Name()
		fmt.Fprintf(&buf, "    %q: %sType,\n", serviceName, tsServiceName)
	}
	fmt.Fprintf(&buf, "};\n\n")
	fmt.Fprintf(&buf, "export const AllServiceImpls = {\n")
	for _, serviceName := range orderedKeys {
		serviceObj := service.ServiceMap[serviceName]
		serviceType := reflect.TypeOf(serviceObj)
		tsServiceName := serviceType.Elem().Name()
		fmt.Fprintf(&buf, "    %q: %s,\n", serviceName, tsServiceName)
	}
	fmt.Fprintf(&buf, "};\n")
	written, err := utilfn.WriteFileIfDifferent(fileName, buf.Bytes())
	if !written {
		fmt.Fprintf(os.Stderr, "no changes to %s\n", fileName)
	}
	return err
}

func generateDshClientApiFile(tsTypeMap map[reflect.Type]string) error {
	fileName := "frontend/app/store/dshclientapi.ts"
	var buf bytes.Buffer
	declMap := dshrpc.GenerateDshCommandDeclMap()
	fmt.Fprintf(os.Stderr, "generating dshclientapi file to %s\n", fileName)
	fmt.Fprintf(&buf, "// Copyright 2026, Command Line Inc.\n")
	fmt.Fprintf(&buf, "// SPDX-License-Identifier: Apache-2.0\n\n")
	fmt.Fprintf(&buf, "// generated by cmd/generate/main-generatets.go\n\n")
	fmt.Fprintf(&buf, "import { DshClient } from \"./dshclient\";\n\n")
	fmt.Fprintf(&buf, "export interface MockRpcClient {\n")
	fmt.Fprintf(&buf, "    mockDshRpcCall(client: DshClient, command: string, data: any, opts?: RpcOpts): Promise<any>;\n")
	fmt.Fprintf(&buf, "    mockDshRpcStream(client: DshClient, command: string, data: any, opts?: RpcOpts): AsyncGenerator<any, void, boolean>;\n")
	fmt.Fprintf(&buf, "}\n\n")
	orderedKeys := utilfn.GetOrderedMapKeys(declMap)
	fmt.Fprintf(&buf, "// DshServerCommandToDeclMap\n")
	fmt.Fprintf(&buf, "export class RpcApiType {\n")
	fmt.Fprintf(&buf, "    mockClient: MockRpcClient = null;\n\n")
	fmt.Fprintf(&buf, "    setMockRpcClient(client: MockRpcClient): void {\n")
	fmt.Fprintf(&buf, "        this.mockClient = client;\n")
	fmt.Fprintf(&buf, "    }\n\n")
	for _, methodDecl := range orderedKeys {
		methodDecl := declMap[methodDecl]
		methodStr := tsgen.GenerateDshClientApiMethod(methodDecl, tsTypeMap)
		fmt.Fprint(&buf, methodStr)
		fmt.Fprintf(&buf, "\n")
	}
	fmt.Fprintf(&buf, "}\n\n")
	fmt.Fprintf(&buf, "export const RpcApi = new RpcApiType();\n")
	written, err := utilfn.WriteFileIfDifferent(fileName, buf.Bytes())
	if !written {
		fmt.Fprintf(os.Stderr, "no changes to %s\n", fileName)
	}
	return err
}

func main() {
	err := service.ValidateServiceMap()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error validating service map: %v\n", err)
		os.Exit(1)
	}
	tsTypesMap := make(map[reflect.Type]string)
	err = generateTypesFile(tsTypesMap)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating types file: %v\n", err)
		os.Exit(1)
	}
	err = generateServicesFile(tsTypesMap)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating services file: %v\n", err)
		os.Exit(1)
	}
	err = generateDoraEventFile(tsTypesMap)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating dora event file: %v\n", err)
		os.Exit(1)
	}
	err = generateDshClientApiFile(tsTypesMap)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating dshserver file: %v\n", err)
		os.Exit(1)
	}
}
