// Copyright 2026, Command Line Inc.
// SPDX-License-Identifier: Apache-2.0

// generated by cmd/generate/main-generatets.go

declare global {

    // dps.DoraEvent
    type DoraEventName =
        | "blockclose"
        | "connchange"
        | "sysinfo"
        | "controllerstatus"
        | "waveobj:update"
        | "blockfile"
        | "config"
        | "userinput"
        | "route:down"
        | "route:up"
        | "workspace:update"
        | "block:jobstatus"
        | "badge"
    ;

    type DoraEvent = {
        event: DoraEventName;
        scopes?: string[];
        sender?: string;
        persist?: number;
        data?: unknown;
    } & (
        { event: "blockclose"; data?: string; } | 
        { event: "connchange"; data?: ConnStatus; } | 
        { event: "sysinfo"; data?: TimeSeriesData; } | 
        { event: "controllerstatus"; data?: BlockControllerRuntimeStatus; } | 
        { event: "waveobj:update"; data?: DoraObjUpdate; } | 
        { event: "blockfile"; data?: WSFileEventData; } | 
        { event: "config"; data?: WatcherUpdate; } | 
        { event: "userinput"; data?: UserInputRequest; } | 
        { event: "route:down"; data?: null; } | 
        { event: "route:up"; data?: null; } | 
        { event: "workspace:update"; data?: null; } | 
        { event: "block:jobstatus"; data?: BlockJobStatusData; } | 
        { event: "badge"; data?: BadgeEvent; }
    );

}

export {}
