// Copyright 2026, Command Line Inc.
// SPDX-License-Identifier: Apache-2.0

// generated by cmd/generate/main-generatets.go

declare global {

    // dconfig.BackgroundConfigType
    type BackgroundConfigType = {
        bg?: string;
        "bg:opacity"?: number;
        "bg:blendmode"?: string;
        "bg:bordercolor"?: string;
        "bg:activebordercolor"?: string;
        "display:name": string;
        "display:order"?: number;
    };

    // baseds.Badge
    type Badge = {
        badgeid: string;
        icon: string;
        color?: string;
        priority: number;
        pidlinked?: boolean;
    };

    // baseds.BadgeEvent
    type BadgeEvent = {
        oref: string;
        clear?: boolean;
        clearall?: boolean;
        clearbyid?: string;
        badge?: Badge;
    };

    // doraobj.Block
    type Block = DoraObj & {
        parentoref?: string;
        runtimeopts?: RuntimeOpts;
        stickers?: StickerType[];
        subblockids?: string[];
        jobid?: string;
    };

    // blockcontroller.BlockControllerRuntimeStatus
    type BlockControllerRuntimeStatus = {
        blockid: string;
        version: number;
        shellprocstatus?: string;
        shellprocconnname?: string;
        shellprocexitcode: number;
    };

    // doraobj.BlockDef
    type BlockDef = {
        files?: {[key: string]: FileDef};
        meta?: MetaType;
    };

    // dshrpc.BlockInfoData
    type BlockInfoData = {
        blockid: string;
        tabid: string;
        workspaceid: string;
        block: Block;
        files: DoraFileInfo[];
    };

    // dshrpc.BlockJobStatusData
    type BlockJobStatusData = {
        blockid: string;
        jobid: string;
        status?: null | "init" | "connected" | "disconnected" | "done";
        versionts: number;
        donereason?: string;
        startuperror?: string;
        cmdexitts?: number;
        cmdexitcode?: number;
        cmdexitsignal?: string;
    };

    // dshrpc.BlocksListEntry
    type BlocksListEntry = {
        windowid: string;
        workspaceid: string;
        tabid: string;
        blockid: string;
        meta: MetaType;
    };

    // dshrpc.BlocksListRequest
    type BlocksListRequest = {
        windowid?: string;
        workspaceid?: string;
    };

    // doraobj.Client
    type Client = DoraObj & {
        windowids: string[];
        hasoldhistory?: boolean;
        tempoid?: string;
        installid?: string;
    };

    // workspaceservice.CloseTabRtnType
    type CloseTabRtnType = {
        closewindow?: boolean;
        newactivetabid?: string;
    };

    // dshrpc.CommandAuthenticateJobManagerData
    type CommandAuthenticateJobManagerData = {
        jobid: string;
        jobauthtoken: string;
    };

    // dshrpc.CommandAuthenticateRtnData
    type CommandAuthenticateRtnData = {
        routeid: string;
        env?: {[key: string]: string};
        initscripttext?: string;
        rpccontext?: RpcContext;
    };

    // dshrpc.CommandAuthenticateToJobData
    type CommandAuthenticateToJobData = {
        jobaccesstoken: string;
    };

    // dshrpc.CommandAuthenticateTokenData
    type CommandAuthenticateTokenData = {
        token: string;
    };

    // dshrpc.CommandBadgeWatchPidData
    type CommandBadgeWatchPidData = {
        pid: number;
        oref: ORef;
        badgeid: string;
    };

    // dshrpc.CommandBlockInputData
    type CommandBlockInputData = {
        blockid: string;
        inputdata64?: string;
        signame?: string;
        termsize?: TermSize;
    };

    // dshrpc.CommandCaptureBlockScreenshotData
    type CommandCaptureBlockScreenshotData = {
        blockid: string;
    };

    // dshrpc.CommandControllerAppendOutputData
    type CommandControllerAppendOutputData = {
        blockid: string;
        data64: string;
    };

    // dshrpc.CommandControllerResyncData
    type CommandControllerResyncData = {
        forcerestart?: boolean;
        tabid: string;
        blockid: string;
        rtopts?: RuntimeOpts;
    };

    // dshrpc.CommandCreateBlockData
    type CommandCreateBlockData = {
        tabid: string;
        blockdef: BlockDef;
        rtopts?: RuntimeOpts;
        magnified?: boolean;
        ephemeral?: boolean;
        focused?: boolean;
        targetblockid?: string;
        targetaction?: string;
    };

    // dshrpc.CommandCreateSubBlockData
    type CommandCreateSubBlockData = {
        parentblockid: string;
        blockdef: BlockDef;
    };

    // dshrpc.CommandDebugTermData
    type CommandDebugTermData = {
        blockid: string;
        size: number;
    };

    // dshrpc.CommandDebugTermRtnData
    type CommandDebugTermRtnData = {
        offset: number;
        data64: string;
    };

    // dshrpc.CommandDeleteBlockData
    type CommandDeleteBlockData = {
        blockid: string;
    };

    // dshrpc.CommandDeleteFileData
    type CommandDeleteFileData = {
        path: string;
        recursive: boolean;
    };

    // dshrpc.CommandDisposeData
    type CommandDisposeData = {
        routeid: string;
    };

    // dshrpc.CommandDoraFileReadStreamData
    type CommandDoraFileReadStreamData = {
        zoneid: string;
        name: string;
        streammeta: StreamMeta;
    };

    // dshrpc.CommandElectronDecryptData
    type CommandElectronDecryptData = {
        ciphertext: string;
    };

    // dshrpc.CommandElectronDecryptRtnData
    type CommandElectronDecryptRtnData = {
        plaintext: string;
        storagebackend: string;
    };

    // dshrpc.CommandElectronEncryptData
    type CommandElectronEncryptData = {
        plaintext: string;
    };

    // dshrpc.CommandElectronEncryptRtnData
    type CommandElectronEncryptRtnData = {
        ciphertext: string;
        storagebackend: string;
    };

    // dshrpc.CommandEventReadHistoryData
    type CommandEventReadHistoryData = {
        event: string;
        scope: string;
        maxitems: number;
    };

    // dshrpc.CommandFileCopyData
    type CommandFileCopyData = {
        srcuri: string;
        desturi: string;
        opts?: FileCopyOpts;
    };

    // dshrpc.CommandFileStreamData
    type CommandFileStreamData = {
        info: FileInfo;
        byterange?: string;
        streammeta: StreamMeta;
    };

    // dshrpc.CommandGetMetaData
    type CommandGetMetaData = {
        oref: ORef;
    };

    // dshrpc.CommandGetRTInfoData
    type CommandGetRTInfoData = {
        oref: ORef;
    };

    // dshrpc.CommandGetTempDirData
    type CommandGetTempDirData = {
        filename?: string;
    };

    // dshrpc.CommandJobCmdExitedData
    type CommandJobCmdExitedData = {
        jobid: string;
        exitcode?: number;
        exitsignal?: string;
        exiterr?: string;
        exitts?: number;
    };

    // dshrpc.CommandJobConnectRtnData
    type CommandJobConnectRtnData = {
        seq: number;
        streamdone?: boolean;
        streamerror?: string;
        hasexited?: boolean;
        exitcode?: number;
        exitsignal?: string;
        exiterr?: string;
    };

    // dshrpc.CommandJobControllerAttachJobData
    type CommandJobControllerAttachJobData = {
        jobid: string;
        blockid: string;
    };

    // dshrpc.CommandJobControllerStartJobData
    type CommandJobControllerStartJobData = {
        connname: string;
        jobkind: string;
        cmd: string;
        args: string[];
        env: {[key: string]: string};
        termsize?: TermSize;
    };

    // dshrpc.CommandJobInputData
    type CommandJobInputData = {
        jobid: string;
        inputsessionid?: string;
        seqnum?: number;
        inputdata64?: string;
        signame?: string;
        termsize?: TermSize;
    };

    // dshrpc.CommandJobPrepareConnectData
    type CommandJobPrepareConnectData = {
        streammeta: StreamMeta;
        seq: number;
        termsize: TermSize;
    };

    // dshrpc.CommandJobStartStreamData
    type CommandJobStartStreamData = object;

    // dshrpc.CommandMessageData
    type CommandMessageData = {
        message: string;
    };

    // dshrpc.CommandRemoteDisconnectFromJobManagerData
    type CommandRemoteDisconnectFromJobManagerData = {
        jobid: string;
    };

    // dshrpc.CommandRemoteFileMultiInfoData
    type CommandRemoteFileMultiInfoData = {
        cwd: string;
        paths: string[];
    };

    // dshrpc.CommandRemoteFileStreamData
    type CommandRemoteFileStreamData = {
        path: string;
        byterange?: string;
        streammeta: StreamMeta;
    };

    // dshrpc.CommandRemoteListEntriesData
    type CommandRemoteListEntriesData = {
        path: string;
        opts?: FileListOpts;
    };

    // dshrpc.CommandRemoteListEntriesRtnData
    type CommandRemoteListEntriesRtnData = {
        fileinfo?: FileInfo[];
    };

    // dshrpc.CommandRemoteProcessListData
    type CommandRemoteProcessListData = {
        widgetid?: string;
        sortby?: string;
        sortdesc?: boolean;
        start?: number;
        limit?: number;
        textsearch?: string;
        lastpidorder?: boolean;
        keepalive?: boolean;
    };

    // dshrpc.CommandRemoteProcessSignalData
    type CommandRemoteProcessSignalData = {
        pid: number;
        signal: string;
    };

    // dshrpc.CommandRemoteReconnectToJobManagerData
    type CommandRemoteReconnectToJobManagerData = {
        jobid: string;
        jobauthtoken: string;
        mainserverjwttoken: string;
        jobmanagerpid: number;
        jobmanagerstartts: number;
    };

    // dshrpc.CommandRemoteReconnectToJobManagerRtnData
    type CommandRemoteReconnectToJobManagerRtnData = {
        success: boolean;
        jobmanagergone: boolean;
        error?: string;
    };

    // dshrpc.CommandRemoteStartJobData
    type CommandRemoteStartJobData = {
        cmd: string;
        args: string[];
        env: {[key: string]: string};
        termsize: TermSize;
        streammeta?: StreamMeta;
        jobauthtoken: string;
        jobid: string;
        mainserverjwttoken: string;
        clientid: string;
        publickeybase64: string;
    };

    // dshrpc.CommandRemoteTerminateJobManagerData
    type CommandRemoteTerminateJobManagerData = {
        jobid: string;
        jobmanagerpid: number;
        jobmanagerstartts: number;
    };

    // dshrpc.CommandResolveIdsData
    type CommandResolveIdsData = {
        blockid: string;
        ids: string[];
    };

    // dshrpc.CommandResolveIdsRtnData
    type CommandResolveIdsRtnData = {
        resolvedids: {[key: string]: ORef};
    };

    // dshrpc.CommandSetMetaData
    type CommandSetMetaData = {
        oref: ORef;
        meta: MetaType;
    };

    // dshrpc.CommandSetRTInfoData
    type CommandSetRTInfoData = {
        oref: ORef;
        data: ObjRTInfo;
        delete?: boolean;
    };

    // dshrpc.CommandStartJobData
    type CommandStartJobData = {
        cmd: string;
        args: string[];
        env: {[key: string]: string};
        termsize: TermSize;
        streammeta?: StreamMeta;
    };

    // dshrpc.CommandStartJobRtnData
    type CommandStartJobRtnData = {
        cmdpid: number;
        cmdstartts: number;
        jobmanagerpid: number;
        jobmanagerstartts: number;
    };

    // dshrpc.CommandStreamAckData
    type CommandStreamAckData = {
        id: string;
        seq: number;
        rwnd: number;
        fin?: boolean;
        delay?: number;
        cancel?: boolean;
        error?: string;
    };

    // dshrpc.CommandStreamData
    type CommandStreamData = {
        id: string;
        seq: number;
        data64?: string;
        eof?: boolean;
        error?: string;
    };

    // dshrpc.CommandTermGetScrollbackLinesData
    type CommandTermGetScrollbackLinesData = {
        linestart: number;
        lineend: number;
        lastcommand: boolean;
    };

    // dshrpc.CommandTermGetScrollbackLinesRtnData
    type CommandTermGetScrollbackLinesRtnData = {
        totallines: number;
        linestart: number;
        lines: string[];
        lastupdated: number;
    };

    // dshrpc.CommandVarData
    type CommandVarData = {
        key: string;
        val?: string;
        remove?: boolean;
        zoneid: string;
        filename: string;
    };

    // dshrpc.CommandVarResponseData
    type CommandVarResponseData = {
        key: string;
        val: string;
        exists: boolean;
    };

    // dshrpc.CommandWaitForRouteData
    type CommandWaitForRouteData = {
        routeid: string;
        waitms: number;
    };

    // dshrpc.CommandWebSelectorData
    type CommandWebSelectorData = {
        workspaceid: string;
        blockid: string;
        tabid: string;
        selector: string;
        opts?: WebSelectorOpts;
    };

    // dshrpc.CommandWriteTempFileData
    type CommandWriteTempFileData = {
        filename: string;
        data64: string;
    };

    // dconfig.ConfigError
    type ConfigError = {
        file: string;
        err: string;
    };

    // dconfig.ConnKeywords
    type ConnKeywords = {
        "conn:wshenabled"?: boolean;
        "conn:askbeforewshinstall"?: boolean;
        "conn:wshpath"?: string;
        "conn:shellpath"?: string;
        "conn:ignoresshconfig"?: boolean;
        "display:hidden"?: boolean;
        "display:order"?: number;
        "term:*"?: boolean;
        "term:fontsize"?: number;
        "term:fontfamily"?: string;
        "term:theme"?: string;
        "term:durable"?: boolean;
        "cmd:env"?: {[key: string]: string};
        "cmd:initscript"?: string;
        "cmd:initscript.sh"?: string;
        "cmd:initscript.bash"?: string;
        "cmd:initscript.zsh"?: string;
        "cmd:initscript.pwsh"?: string;
        "cmd:initscript.fish"?: string;
        "ssh:user"?: string;
        "ssh:hostname"?: string;
        "ssh:port"?: string;
        "ssh:identityfile"?: string[];
        "ssh:passwordsecretname"?: string;
        "ssh:batchmode"?: boolean;
        "ssh:pubkeyauthentication"?: boolean;
        "ssh:passwordauthentication"?: boolean;
        "ssh:kbdinteractiveauthentication"?: boolean;
        "ssh:preferredauthentications"?: string[];
        "ssh:addkeystoagent"?: boolean;
        "ssh:identityagent"?: string;
        "ssh:identitiesonly"?: boolean;
        "ssh:proxyjump"?: string[];
        "ssh:userknownhostsfile"?: string[];
        "ssh:globalknownhostsfile"?: string[];
    };

    // dshrpc.ConnStatus
    type ConnStatus = {
        status: string;
        connhealthstatus?: string;
        wshenabled: boolean;
        connection: string;
        connected: boolean;
        hasconnected: boolean;
        activeconnnum: number;
        error?: string;
        wsherror?: string;
        nowshreason?: string;
        wshversion?: string;
        lastactivitybeforestalledtime?: number;
        keepalivesenttime?: number;
    };

    // dshrpc.CpuDataRequest
    type CpuDataRequest = {
        id: string;
        count: number;
    };


    // filestore.DoraFile
    type DoraFile = {
        zoneid: string;
        name: string;
        opts: FileOpts;
        createdts: number;
        size: number;
        modts: number;
        meta: {[key: string]: any};
    };

    // dshrpc.DoraFileInfo
    type DoraFileInfo = {
        zoneid: string;
        name: string;
        opts: FileOpts;
        createdts: number;
        size: number;
        modts: number;
        meta: {[key: string]: any};
    };

    // dshrpc.DoraInfoData
    type DoraInfoData = {
        version: string;
        clientid: string;
        buildtime: string;
        configdir: string;
        datadir: string;
    };

    // dshrpc.DoraNotificationOptions
    type DoraNotificationOptions = {
        title?: string;
        body?: string;
        silent?: boolean;
    };

    // doraobj.DoraObj
    type DoraObj = {
        otype: string;
        oid: string;
        version: number;
        meta: MetaType;
    };

    // doraobj.DoraObjUpdate
    type DoraObjUpdate = {
        updatetype: string;
        otype: string;
        oid: string;
        obj?: DoraObj;
    };

    // doraobj.Window
    type DoraWindow = DoraObj & {
        workspaceid: string;
        isnew?: boolean;
        pos: Point;
        winsize: WinSize;
        lastfocusts: number;
    };

    // dshrpc.DshServerCommandMeta
    type DshServerCommandMeta = {
        commandtype: string;
    };

    // dshrpc.FileCopyOpts
    type FileCopyOpts = {
        overwrite?: boolean;
        recursive?: boolean;
        merge?: boolean;
        timeout?: number;
    };

    // dshrpc.FileData
    type FileData = {
        info?: FileInfo;
        data64?: string;
        entries?: FileInfo[];
        at?: FileDataAt;
    };

    // dshrpc.FileDataAt
    type FileDataAt = {
        offset: number;
        size?: number;
    };

    // doraobj.FileDef
    type FileDef = {
        content?: string;
        meta?: {[key: string]: any};
    };

    // dshrpc.FileInfo
    type FileInfo = {
        path: string;
        dir?: string;
        name?: string;
        staterror?: string;
        notfound?: boolean;
        opts?: FileOpts;
        size?: number;
        meta?: {[key: string]: any};
        mode?: number;
        modestr?: string;
        modtime?: number;
        isdir?: boolean;
        supportsmkdir?: boolean;
        mimetype?: string;
        readonly?: boolean;
    };

    // dshrpc.FileListData
    type FileListData = {
        path: string;
        opts?: FileListOpts;
    };

    // dshrpc.FileListOpts
    type FileListOpts = {
        all?: boolean;
        offset?: number;
        limit?: number;
    };

    // dshrpc.FileOpts
    type FileOpts = {
        maxsize?: number;
        circular?: boolean;
        ijson?: boolean;
        ijsonbudget?: number;
        truncate?: boolean;
        append?: boolean;
    };

    // dshrpc.FocusedBlockData
    type FocusedBlockData = {
        blockid: string;
        viewtype: string;
        controller: string;
        connname: string;
        blockmeta: MetaType;
        termjobstatus?: BlockJobStatusData;
        connstatus?: ConnStatus;
        termshellintegrationstatus?: string;
        termlastcommand?: string;
    };

    // dconfig.FullConfigType
    type FullConfigType = {
        settings: SettingsType;
        mimetypes: {[key: string]: MimeTypeConfigType};
        defaultwidgets: {[key: string]: WidgetConfigType};
        widgets: {[key: string]: WidgetConfigType};
        presets: {[key: string]: MetaType};
        backgrounds: {[key: string]: BackgroundConfigType};
        termthemes: {[key: string]: TermThemeType};
        connections: {[key: string]: ConnKeywords};
        configerrors: ConfigError[];
        version: string;
        buildtime: string;
    };

    // doraobj.Job
    type Job = DoraObj & {
        connection: string;
        jobkind: string;
        cmd: string;
        cmdargs?: string[];
        cmdenv?: {[key: string]: string};
        jobauthtoken: string;
        attachedblockid?: string;
        waveversion?: string;
        terminateonreconnect?: boolean;
        jobmanagerstatus: string;
        jobmanagerdonereason?: string;
        jobmanagerstartuperror?: string;
        jobmanagerpid?: number;
        jobmanagerstartts?: number;
        cmdpid?: number;
        cmdstartts?: number;
        cmdtermsize: TermSize;
        cmdexitts?: number;
        cmdexitcode?: number;
        cmdexitsignal?: string;
        cmdexiterror?: string;
        streamdone?: boolean;
        streamerror?: string;
    };

    // dshrpc.JobManagerStatusUpdate
    type JobManagerStatusUpdate = {
        jobid: string;
        jobmanagerstatus: string;
    };

    // doraobj.LayoutActionData
    type LayoutActionData = {
        actiontype: string;
        actionid: string;
        blockid: string;
        nodesize?: number;
        indexarr?: number[];
        focused: boolean;
        magnified: boolean;
        ephemeral: boolean;
        targetblockid?: string;
        position?: string;
    };

    // doraobj.LayoutState
    type LayoutState = DoraObj & {
        rootnode?: any;
        magnifiednodeid?: string;
        focusednodeid?: string;
        leaforder?: LeafOrderEntry[];
        pendingbackendactions?: LayoutActionData[];
    };

    // doraobj.LeafOrderEntry
    type LeafOrderEntry = {
        nodeid: string;
        blockid: string;
    };

    // doraobj.MetaTSType
    type MetaType = {
        view?: string;
        controller?: string;
        file?: string;
        url?: string;
        pinnedurl?: string;
        connection?: string;
        edit?: boolean;
        history?: string[];
        "history:forward"?: string[];
        "display:name"?: string;
        "display:order"?: number;
        icon?: string;
        "icon:color"?: string;
        "frame:*"?: boolean;
        frame?: boolean;
        "frame:bordercolor"?: string;
        "frame:activebordercolor"?: string;
        "frame:title"?: string;
        "frame:icon"?: string;
        "frame:text"?: string;
        "cmd:*"?: boolean;
        cmd?: string;
        "cmd:interactive"?: boolean;
        "cmd:login"?: boolean;
        "cmd:persistent"?: boolean;
        "cmd:runonstart"?: boolean;
        "cmd:clearonstart"?: boolean;
        "cmd:runonce"?: boolean;
        "cmd:closeonexit"?: boolean;
        "cmd:closeonexitforce"?: boolean;
        "cmd:closeonexitdelay"?: number;
        "cmd:nowsh"?: boolean;
        "cmd:args"?: string[];
        "cmd:shell"?: boolean;
        "cmd:allowconnchange"?: boolean;
        "cmd:jwt"?: boolean;
        "cmd:env"?: {[key: string]: string};
        "cmd:cwd"?: string;
        "cmd:initscript"?: string;
        "cmd:initscript.sh"?: string;
        "cmd:initscript.bash"?: string;
        "cmd:initscript.zsh"?: string;
        "cmd:initscript.pwsh"?: string;
        "cmd:initscript.fish"?: string;
        "ai:*"?: boolean;
        "ai:preset"?: string;
        "ai:apitype"?: string;
        "ai:baseurl"?: string;
        "ai:apitoken"?: string;
        "ai:name"?: string;
        "ai:model"?: string;
        "ai:orgid"?: string;
        "ai:apiversion"?: string;
        "ai:maxtokens"?: number;
        "ai:timeoutms"?: number;
        "aifilediff:chatid"?: string;
        "aifilediff:toolcallid"?: string;
        "editor:*"?: boolean;
        "editor:minimapenabled"?: boolean;
        "editor:stickyscrollenabled"?: boolean;
        "editor:wordwrap"?: boolean;
        "editor:fontsize"?: number;
        "graph:*"?: boolean;
        "graph:numpoints"?: number;
        "graph:metrics"?: string[];
        "sysinfo:type"?: string;
        "tab:flagcolor"?: string;
        "tab:background"?: string;
        "bg:*"?: boolean;
        bg?: string;
        "bg:opacity"?: number;
        "bg:blendmode"?: string;
        "bg:bordercolor"?: string;
        "bg:activebordercolor"?: string;
        "layout:vtabbarwidth"?: number;
        "layout:widgetsvisible"?: boolean;
        "waveai:panelopen"?: boolean;
        "waveai:panelwidth"?: number;
        "waveai:model"?: string;
        "waveai:chatid"?: string;
        "waveai:widgetcontext"?: boolean;
        "term:*"?: boolean;
        "term:fontsize"?: number;
        "term:fontfamily"?: string;
        "term:mode"?: string;
        "term:theme"?: string;
        "term:localshellpath"?: string;
        "term:localshellopts"?: string[];
        "term:scrollback"?: number;
        "term:transparency"?: number;
        "term:allowbracketedpaste"?: boolean;
        "term:shiftenternewline"?: boolean;
        "term:macoptionismeta"?: boolean;
        "term:cursor"?: string;
        "term:cursorblink"?: boolean;
        "term:conndebug"?: string;
        "term:bellsound"?: boolean;
        "term:bellindicator"?: boolean;
        "term:osc52"?: string;
        "term:durable"?: boolean;
        "web:zoom"?: number;
        "web:hidenav"?: boolean;
        "web:partition"?: string;
        "web:useragenttype"?: string;
        "markdown:fontsize"?: number;
        "markdown:fixedfontsize"?: number;
        count?: number;
    };

    // tsgenmeta.MethodMeta
    type MethodMeta = {
        Desc: string;
        ArgNames: string[];
        ReturnDesc: string;
    };

    // dconfig.MimeTypeConfigType
    type MimeTypeConfigType = {
        icon: string;
        color: string;
    };

    // doraobj.ORef
    type ORef = string;

    // doraobj.ObjRTInfo
    type ObjRTInfo = {
        "shell:hascurcwd"?: boolean;
        "shell:state"?: string;
        "shell:type"?: string;
        "shell:version"?: string;
        "shell:uname"?: string;
        "shell:integration"?: boolean;
        "shell:omz"?: boolean;
        "shell:comp"?: string;
        "shell:inputempty"?: boolean;
        "shell:lastcmd"?: string;
        "shell:lastcmdexitcode"?: number;
        "builder:layout"?: {[key: string]: number};
        "builder:appid"?: string;
        "builder:env"?: {[key: string]: string};
        "waveai:chatid"?: string;
        "waveai:mode"?: string;
        "waveai:maxoutputtokens"?: number;
    };

    // dshrpc.PathCommandData
    type PathCommandData = {
        pathtype: string;
        open: boolean;
        openexternal: boolean;
        tabid: string;
    };

    // doraobj.Point
    type Point = {
        x: number;
        y: number;
    };

    // dshrpc.ProcessInfo
    type ProcessInfo = {
        pid: number;
        ppid?: number;
        command?: string;
        status?: string;
        user?: string;
        mem: number;
        mempct: number;
        cpu: number;
        numthreads: number;
        gone?: boolean;
    };

    // dshrpc.ProcessListResponse
    type ProcessListResponse = {
        processes: ProcessInfo[];
        summary: ProcessSummary;
        ts: number;
        hascpu?: boolean;
        platform?: string;
        totalcount?: number;
        filteredcount?: number;
    };

    // dshrpc.ProcessSummary
    type ProcessSummary = {
        total: number;
        load1?: number;
        load5?: number;
        load15?: number;
        memtotal?: number;
        memused?: number;
        memfree?: number;
        numcpu?: number;
        cpusum?: number;
    };

    // dshrpc.RemoteInfo
    type RemoteInfo = {
        clientarch: string;
        clientos: string;
        clientversion: string;
        shell: string;
        homedir: string;
    };

    // dshrpc.RpcContext
    type RpcContext = {
        sockname?: string;
        routeid: string;
        procroute?: boolean;
        blockid?: string;
        conn?: string;
        isrouter?: boolean;
    };

    // dshutil.RpcMessage
    type RpcMessage = {
        command?: string;
        reqid?: string;
        resid?: string;
        timeout?: number;
        route?: string;
        source?: string;
        cont?: boolean;
        cancel?: boolean;
        error?: string;
        datatype?: string;
        data?: any;
    };

    // dshrpc.RpcOpts
    type RpcOpts = {
        timeout?: number;
        noresponse?: boolean;
        route?: string;
    };

    // doraobj.RuntimeOpts
    type RuntimeOpts = {
        termsize?: TermSize;
        winsize?: WinSize;
    };

    // dconfig.SettingsType
    type SettingsType = {
        "app:*"?: boolean;
        "app:globalhotkey"?: string;
        "app:dismissarchitecturewarning"?: boolean;
        "app:defaultnewblock"?: string;
        "app:showoverlayblocknums"?: boolean;
        "app:ctrlvpaste"?: boolean;
        "app:confirmquit"?: boolean;
        "app:hideaibutton"?: boolean;
        "app:disablectrlshiftarrows"?: boolean;
        "app:disablectrlshiftdisplay"?: boolean;
        "app:focusfollowscursor"?: string;
        "app:tabbar"?: string;
        "term:*"?: boolean;
        "term:fontsize"?: number;
        "term:fontfamily"?: string;
        "term:theme"?: string;
        "term:disablewebgl"?: boolean;
        "term:localshellpath"?: string;
        "term:localshellopts"?: string[];
        "term:gitbashpath"?: string;
        "term:scrollback"?: number;
        "term:copyonselect"?: boolean;
        "term:transparency"?: number;
        "term:allowbracketedpaste"?: boolean;
        "term:shiftenternewline"?: boolean;
        "term:macoptionismeta"?: boolean;
        "term:cursor"?: string;
        "term:cursorblink"?: boolean;
        "term:bellsound"?: boolean;
        "term:bellindicator"?: boolean;
        "term:osc52"?: string;
        "term:durable"?: boolean;
        "term:showsplitbuttons"?: boolean;
        "term:trimtrailingwhitespace"?: boolean;
        "editor:minimapenabled"?: boolean;
        "editor:stickyscrollenabled"?: boolean;
        "editor:wordwrap"?: boolean;
        "editor:fontsize"?: number;
        "editor:inlinediff"?: boolean;
        "web:*"?: boolean;
        "web:openlinksinternally"?: boolean;
        "web:defaulturl"?: string;
        "web:defaultsearch"?: string;
        "autoupdate:*"?: boolean;
        "autoupdate:enabled"?: boolean;
        "autoupdate:intervalms"?: number;
        "autoupdate:installonquit"?: boolean;
        "autoupdate:channel"?: string;
        "markdown:fontsize"?: number;
        "markdown:fixedfontsize"?: number;
        "preview:showhiddenfiles"?: boolean;
        "preview:defaultsort"?: string;
        "tab:preset"?: string;
        "tab:confirmclose"?: boolean;
        "tab:background"?: string;
        "widget:*"?: boolean;
        "widget:showhelp"?: boolean;
        "window:*"?: boolean;
        "window:fullscreenonlaunch"?: boolean;
        "window:transparent"?: boolean;
        "window:blur"?: boolean;
        "window:opacity"?: number;
        "window:bgcolor"?: string;
        "window:reducedmotion"?: boolean;
        "window:tilegapsize"?: number;
        "window:showmenubar"?: boolean;
        "window:nativetitlebar"?: boolean;
        "window:disablehardwareacceleration"?: boolean;
        "window:maxtabcachesize"?: number;
        "window:magnifiedblockopacity"?: number;
        "window:magnifiedblocksize"?: number;
        "window:magnifiedblockblurprimarypx"?: number;
        "window:magnifiedblockblursecondarypx"?: number;
        "window:confirmclose"?: boolean;
        "window:savelastwindow"?: boolean;
        "window:dimensions"?: string;
        "window:zoom"?: number;
        "conn:*"?: boolean;
        "conn:askbeforewshinstall"?: boolean;
        "conn:wshenabled"?: boolean;
        "conn:localhostdisplayname"?: string;
        "debug:*"?: boolean;
        "debug:pprofport"?: number;
        "debug:pprofmemprofilerate"?: number;
        "debug:webglstatus"?: boolean;
    };

    // doraobj.StickerClickOptsType
    type StickerClickOptsType = {
        sendinput?: string;
        createblock?: BlockDef;
    };

    // doraobj.StickerDisplayOptsType
    type StickerDisplayOptsType = {
        icon: string;
        imgsrc: string;
        svgblob?: string;
    };

    // doraobj.StickerType
    type StickerType = {
        stickertype: string;
        style: {[key: string]: any};
        clickopts?: StickerClickOptsType;
        display: StickerDisplayOptsType;
    };

    // dshrpc.StreamMeta
    type StreamMeta = {
        id: string;
        rwnd: number;
        readerrouteid: string;
        writerrouteid: string;
    };

    // dps.SubscriptionRequest
    type SubscriptionRequest = {
        event: string;
        scopes?: string[];
        allscopes?: boolean;
    };

    // doraobj.Tab
    type Tab = DoraObj & {
        name: string;
        layoutstate: string;
        blockids: string[];
    };

    // doraobj.TermSize
    type TermSize = {
        rows: number;
        cols: number;
    };

    // dconfig.TermThemeType
    type TermThemeType = {
        "display:name": string;
        "display:order": number;
        black: string;
        red: string;
        green: string;
        yellow: string;
        blue: string;
        magenta: string;
        cyan: string;
        white: string;
        brightBlack: string;
        brightRed: string;
        brightGreen: string;
        brightYellow: string;
        brightBlue: string;
        brightMagenta: string;
        brightCyan: string;
        brightWhite: string;
        gray: string;
        cmdtext: string;
        foreground: string;
        selectionBackground: string;
        background: string;
        cursor: string;
    };

    // dshrpc.TimeSeriesData
    type TimeSeriesData = {
        ts: number;
        values: {[key: string]: number};
    };

    // doraobj.UIContext
    type UIContext = {
        windowid: string;
        activetabid: string;
    };

    // userinput.UserInputRequest
    type UserInputRequest = {
        requestid: string;
        querytext: string;
        responsetype: string;
        title: string;
        markdown: boolean;
        timeoutms: number;
        checkboxmsg: string;
        publictext: boolean;
        oklabel?: string;
        cancellabel?: string;
    };

    // userinput.UserInputResponse
    type UserInputResponse = {
        type: string;
        requestid: string;
        text?: string;
        confirm?: boolean;
        errormsg?: string;
        checkboxstat?: boolean;
    };

    type WSCommandType = {
        wscommand: string;
    } & ( WSRpcCommand );

    // eventbus.WSEventType
    type WSEventType = {
        eventtype: string;
        oref?: string;
        data: any;
    };

    // dps.WSFileEventData
    type WSFileEventData = {
        zoneid: string;
        filename: string;
        fileop: string;
        data64: string;
    };

    // webcmd.WSRpcCommand
    type WSRpcCommand = {
        wscommand: "rpc";
        message: RpcMessage;
    };

    // dconfig.WatcherUpdate
    type WatcherUpdate = {
        fullconfig: FullConfigType;
    };

    // service.WebCallType
    type WebCallType = {
        service: string;
        method: string;
        uicontext?: UIContext;
        args: any[];
    };

    // service.WebReturnType
    type WebReturnType = {
        success?: boolean;
        error?: string;
        data?: any;
        updates?: DoraObjUpdate[];
    };

    // dshrpc.WebSelectorOpts
    type WebSelectorOpts = {
        all?: boolean;
        inner?: boolean;
    };

    // dconfig.WidgetConfigType
    type WidgetConfigType = {
        "display:order"?: number;
        "display:hidden"?: boolean;
        icon?: string;
        color?: string;
        label?: string;
        description?: string;
        workspaces?: string[];
        magnified?: boolean;
        blockdef: BlockDef;
    };

    // doraobj.WinSize
    type WinSize = {
        width: number;
        height: number;
    };

    // doraobj.Workspace
    type Workspace = DoraObj & {
        name?: string;
        icon?: string;
        color?: string;
        tabids: string[];
        activetabid: string;
    };

    // dshrpc.WorkspaceInfoData
    type WorkspaceInfoData = {
        windowid: string;
        workspacedata: Workspace;
    };

    // doraobj.WorkspaceListEntry
    type WorkspaceListEntry = {
        workspaceid: string;
        windowid: string;
    };

}

export {}
