// Copyright 2026, Command Line Inc.
// SPDX-License-Identifier: Apache-2.0

// generated by cmd/generate/main-generatets.go

import { DshClient } from "./dshclient";

export interface MockRpcClient {
    mockDshRpcCall(client: DshClient, command: string, data: any, opts?: RpcOpts): Promise<any>;
    mockDshRpcStream(client: DshClient, command: string, data: any, opts?: RpcOpts): AsyncGenerator<any, void, boolean>;
}

// DshServerCommandToDeclMap
export class RpcApiType {
    mockClient: MockRpcClient = null;

    setMockRpcClient(client: MockRpcClient): void {
        this.mockClient = client;
    }

    // command "authenticate" [call]
    AuthenticateCommand(client: DshClient, data: string, opts?: RpcOpts): Promise<CommandAuthenticateRtnData> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "authenticate", data, opts);
        return client.wshRpcCall("authenticate", data, opts);
    }

    // command "authenticatejobmanager" [call]
    AuthenticateJobManagerCommand(client: DshClient, data: CommandAuthenticateJobManagerData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "authenticatejobmanager", data, opts);
        return client.wshRpcCall("authenticatejobmanager", data, opts);
    }

    // command "authenticatejobmanagerverify" [call]
    AuthenticateJobManagerVerifyCommand(client: DshClient, data: CommandAuthenticateJobManagerData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "authenticatejobmanagerverify", data, opts);
        return client.wshRpcCall("authenticatejobmanagerverify", data, opts);
    }

    // command "authenticatetojobmanager" [call]
    AuthenticateToJobManagerCommand(client: DshClient, data: CommandAuthenticateToJobData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "authenticatetojobmanager", data, opts);
        return client.wshRpcCall("authenticatetojobmanager", data, opts);
    }

    // command "authenticatetoken" [call]
    AuthenticateTokenCommand(client: DshClient, data: CommandAuthenticateTokenData, opts?: RpcOpts): Promise<CommandAuthenticateRtnData> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "authenticatetoken", data, opts);
        return client.wshRpcCall("authenticatetoken", data, opts);
    }

    // command "authenticatetokenverify" [call]
    AuthenticateTokenVerifyCommand(client: DshClient, data: CommandAuthenticateTokenData, opts?: RpcOpts): Promise<CommandAuthenticateRtnData> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "authenticatetokenverify", data, opts);
        return client.wshRpcCall("authenticatetokenverify", data, opts);
    }

    // command "badgewatchpid" [call]
    BadgeWatchPidCommand(client: DshClient, data: CommandBadgeWatchPidData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "badgewatchpid", data, opts);
        return client.wshRpcCall("badgewatchpid", data, opts);
    }

    // command "blockinfo" [call]
    BlockInfoCommand(client: DshClient, data: string, opts?: RpcOpts): Promise<BlockInfoData> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "blockinfo", data, opts);
        return client.wshRpcCall("blockinfo", data, opts);
    }

    // command "blockjobstatus" [call]
    BlockJobStatusCommand(client: DshClient, data: string, opts?: RpcOpts): Promise<BlockJobStatusData> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "blockjobstatus", data, opts);
        return client.wshRpcCall("blockjobstatus", data, opts);
    }

    // command "blockslist" [call]
    BlocksListCommand(client: DshClient, data: BlocksListRequest, opts?: RpcOpts): Promise<BlocksListEntry[]> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "blockslist", data, opts);
        return client.wshRpcCall("blockslist", data, opts);
    }

    // command "captureblockscreenshot" [call]
    CaptureBlockScreenshotCommand(client: DshClient, data: CommandCaptureBlockScreenshotData, opts?: RpcOpts): Promise<string> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "captureblockscreenshot", data, opts);
        return client.wshRpcCall("captureblockscreenshot", data, opts);
    }

    // command "controlgetrouteid" [call]
    ControlGetRouteIdCommand(client: DshClient, opts?: RpcOpts): Promise<string> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "controlgetrouteid", null, opts);
        return client.wshRpcCall("controlgetrouteid", null, opts);
    }

    // command "controllerappendoutput" [call]
    ControllerAppendOutputCommand(client: DshClient, data: CommandControllerAppendOutputData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "controllerappendoutput", data, opts);
        return client.wshRpcCall("controllerappendoutput", data, opts);
    }

    // command "controllerdestroy" [call]
    ControllerDestroyCommand(client: DshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "controllerdestroy", data, opts);
        return client.wshRpcCall("controllerdestroy", data, opts);
    }

    // command "controllerinput" [call]
    ControllerInputCommand(client: DshClient, data: CommandBlockInputData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "controllerinput", data, opts);
        return client.wshRpcCall("controllerinput", data, opts);
    }

    // command "controllerresync" [call]
    ControllerResyncCommand(client: DshClient, data: CommandControllerResyncData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "controllerresync", data, opts);
        return client.wshRpcCall("controllerresync", data, opts);
    }

    // command "createblock" [call]
    CreateBlockCommand(client: DshClient, data: CommandCreateBlockData, opts?: RpcOpts): Promise<ORef> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "createblock", data, opts);
        return client.wshRpcCall("createblock", data, opts);
    }

    // command "createsubblock" [call]
    CreateSubBlockCommand(client: DshClient, data: CommandCreateSubBlockData, opts?: RpcOpts): Promise<ORef> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "createsubblock", data, opts);
        return client.wshRpcCall("createsubblock", data, opts);
    }

    // command "debugterm" [call]
    DebugTermCommand(client: DshClient, data: CommandDebugTermData, opts?: RpcOpts): Promise<CommandDebugTermRtnData> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "debugterm", data, opts);
        return client.wshRpcCall("debugterm", data, opts);
    }

    // command "deleteblock" [call]
    DeleteBlockCommand(client: DshClient, data: CommandDeleteBlockData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "deleteblock", data, opts);
        return client.wshRpcCall("deleteblock", data, opts);
    }

    // command "deletesubblock" [call]
    DeleteSubBlockCommand(client: DshClient, data: CommandDeleteBlockData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "deletesubblock", data, opts);
        return client.wshRpcCall("deletesubblock", data, opts);
    }

    // command "dispose" [call]
    DisposeCommand(client: DshClient, data: CommandDisposeData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "dispose", data, opts);
        return client.wshRpcCall("dispose", data, opts);
    }

    // command "dorafilereadstream" [call]
    DoraFileReadStreamCommand(client: DshClient, data: CommandDoraFileReadStreamData, opts?: RpcOpts): Promise<DoraFileInfo> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "dorafilereadstream", data, opts);
        return client.wshRpcCall("dorafilereadstream", data, opts);
    }

    // command "dorainfo" [call]
    DoraInfoCommand(client: DshClient, opts?: RpcOpts): Promise<DoraInfoData> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "dorainfo", null, opts);
        return client.wshRpcCall("dorainfo", null, opts);
    }

    // command "electrondecrypt" [call]
    ElectronDecryptCommand(client: DshClient, data: CommandElectronDecryptData, opts?: RpcOpts): Promise<CommandElectronDecryptRtnData> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "electrondecrypt", data, opts);
        return client.wshRpcCall("electrondecrypt", data, opts);
    }

    // command "electronencrypt" [call]
    ElectronEncryptCommand(client: DshClient, data: CommandElectronEncryptData, opts?: RpcOpts): Promise<CommandElectronEncryptRtnData> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "electronencrypt", data, opts);
        return client.wshRpcCall("electronencrypt", data, opts);
    }

    // command "electronsystembell" [call]
    ElectronSystemBellCommand(client: DshClient, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "electronsystembell", null, opts);
        return client.wshRpcCall("electronsystembell", null, opts);
    }

    // command "eventpublish" [call]
    EventPublishCommand(client: DshClient, data: DoraEvent, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "eventpublish", data, opts);
        return client.wshRpcCall("eventpublish", data, opts);
    }

    // command "eventreadhistory" [call]
    EventReadHistoryCommand(client: DshClient, data: CommandEventReadHistoryData, opts?: RpcOpts): Promise<DoraEvent[]> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "eventreadhistory", data, opts);
        return client.wshRpcCall("eventreadhistory", data, opts);
    }

    // command "eventrecv" [call]
    EventRecvCommand(client: DshClient, data: DoraEvent, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "eventrecv", data, opts);
        return client.wshRpcCall("eventrecv", data, opts);
    }

    // command "eventsub" [call]
    EventSubCommand(client: DshClient, data: SubscriptionRequest, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "eventsub", data, opts);
        return client.wshRpcCall("eventsub", data, opts);
    }

    // command "eventunsub" [call]
    EventUnsubCommand(client: DshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "eventunsub", data, opts);
        return client.wshRpcCall("eventunsub", data, opts);
    }

    // command "eventunsuball" [call]
    EventUnsubAllCommand(client: DshClient, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "eventunsuball", null, opts);
        return client.wshRpcCall("eventunsuball", null, opts);
    }

    // command "fileappend" [call]
    FileAppendCommand(client: DshClient, data: FileData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "fileappend", data, opts);
        return client.wshRpcCall("fileappend", data, opts);
    }

    // command "filecopy" [call]
    FileCopyCommand(client: DshClient, data: CommandFileCopyData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "filecopy", data, opts);
        return client.wshRpcCall("filecopy", data, opts);
    }

    // command "filecreate" [call]
    FileCreateCommand(client: DshClient, data: FileData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "filecreate", data, opts);
        return client.wshRpcCall("filecreate", data, opts);
    }

    // command "filedelete" [call]
    FileDeleteCommand(client: DshClient, data: CommandDeleteFileData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "filedelete", data, opts);
        return client.wshRpcCall("filedelete", data, opts);
    }

    // command "fileinfo" [call]
    FileInfoCommand(client: DshClient, data: FileData, opts?: RpcOpts): Promise<FileInfo> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "fileinfo", data, opts);
        return client.wshRpcCall("fileinfo", data, opts);
    }

    // command "filejoin" [call]
    FileJoinCommand(client: DshClient, data: string[], opts?: RpcOpts): Promise<FileInfo> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "filejoin", data, opts);
        return client.wshRpcCall("filejoin", data, opts);
    }

    // command "filelist" [call]
    FileListCommand(client: DshClient, data: FileListData, opts?: RpcOpts): Promise<FileInfo[]> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "filelist", data, opts);
        return client.wshRpcCall("filelist", data, opts);
    }

    // command "fileliststream" [responsestream]
	FileListStreamCommand(client: DshClient, data: FileListData, opts?: RpcOpts): AsyncGenerator<CommandRemoteListEntriesRtnData, void, boolean> {
        if (this.mockClient) return this.mockClient.mockDshRpcStream(client, "fileliststream", data, opts);
        return client.wshRpcStream("fileliststream", data, opts);
    }

    // command "filemkdir" [call]
    FileMkdirCommand(client: DshClient, data: FileData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "filemkdir", data, opts);
        return client.wshRpcCall("filemkdir", data, opts);
    }

    // command "filemove" [call]
    FileMoveCommand(client: DshClient, data: CommandFileCopyData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "filemove", data, opts);
        return client.wshRpcCall("filemove", data, opts);
    }

    // command "fileread" [call]
    FileReadCommand(client: DshClient, data: FileData, opts?: RpcOpts): Promise<FileData> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "fileread", data, opts);
        return client.wshRpcCall("fileread", data, opts);
    }

    // command "filestream" [call]
    FileStreamCommand(client: DshClient, data: CommandFileStreamData, opts?: RpcOpts): Promise<FileInfo> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "filestream", data, opts);
        return client.wshRpcCall("filestream", data, opts);
    }

    // command "filewrite" [call]
    FileWriteCommand(client: DshClient, data: FileData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "filewrite", data, opts);
        return client.wshRpcCall("filewrite", data, opts);
    }

    // command "focuswindow" [call]
    FocusWindowCommand(client: DshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "focuswindow", data, opts);
        return client.wshRpcCall("focuswindow", data, opts);
    }

    // command "getallbadges" [call]
    GetAllBadgesCommand(client: DshClient, opts?: RpcOpts): Promise<BadgeEvent[]> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "getallbadges", null, opts);
        return client.wshRpcCall("getallbadges", null, opts);
    }

    // command "getallvars" [call]
    GetAllVarsCommand(client: DshClient, data: CommandVarData, opts?: RpcOpts): Promise<CommandVarResponseData[]> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "getallvars", data, opts);
        return client.wshRpcCall("getallvars", data, opts);
    }

    // command "getfocusedblockdata" [call]
    GetFocusedBlockDataCommand(client: DshClient, opts?: RpcOpts): Promise<FocusedBlockData> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "getfocusedblockdata", null, opts);
        return client.wshRpcCall("getfocusedblockdata", null, opts);
    }

    // command "getfullconfig" [call]
    GetFullConfigCommand(client: DshClient, opts?: RpcOpts): Promise<FullConfigType> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "getfullconfig", null, opts);
        return client.wshRpcCall("getfullconfig", null, opts);
    }

    // command "getjwtpublickey" [call]
    GetJwtPublicKeyCommand(client: DshClient, opts?: RpcOpts): Promise<string> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "getjwtpublickey", null, opts);
        return client.wshRpcCall("getjwtpublickey", null, opts);
    }

    // command "getmeta" [call]
    GetMetaCommand(client: DshClient, data: CommandGetMetaData, opts?: RpcOpts): Promise<MetaType> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "getmeta", data, opts);
        return client.wshRpcCall("getmeta", data, opts);
    }

    // command "getrtinfo" [call]
    GetRTInfoCommand(client: DshClient, data: CommandGetRTInfoData, opts?: RpcOpts): Promise<ObjRTInfo> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "getrtinfo", data, opts);
        return client.wshRpcCall("getrtinfo", data, opts);
    }

    // command "getsecrets" [call]
    GetSecretsCommand(client: DshClient, data: string[], opts?: RpcOpts): Promise<{[key: string]: string}> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "getsecrets", data, opts);
        return client.wshRpcCall("getsecrets", data, opts);
    }

    // command "getsecretslinuxstoragebackend" [call]
    GetSecretsLinuxStorageBackendCommand(client: DshClient, opts?: RpcOpts): Promise<string> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "getsecretslinuxstoragebackend", null, opts);
        return client.wshRpcCall("getsecretslinuxstoragebackend", null, opts);
    }

    // command "getsecretsnames" [call]
    GetSecretsNamesCommand(client: DshClient, opts?: RpcOpts): Promise<string[]> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "getsecretsnames", null, opts);
        return client.wshRpcCall("getsecretsnames", null, opts);
    }

    // command "gettab" [call]
    GetTabCommand(client: DshClient, data: string, opts?: RpcOpts): Promise<Tab> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "gettab", data, opts);
        return client.wshRpcCall("gettab", data, opts);
    }

    // command "gettempdir" [call]
    GetTempDirCommand(client: DshClient, data: CommandGetTempDirData, opts?: RpcOpts): Promise<string> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "gettempdir", data, opts);
        return client.wshRpcCall("gettempdir", data, opts);
    }

    // command "getupdatechannel" [call]
    GetUpdateChannelCommand(client: DshClient, opts?: RpcOpts): Promise<string> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "getupdatechannel", null, opts);
        return client.wshRpcCall("getupdatechannel", null, opts);
    }

    // command "getvar" [call]
    GetVarCommand(client: DshClient, data: CommandVarData, opts?: RpcOpts): Promise<CommandVarResponseData> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "getvar", data, opts);
        return client.wshRpcCall("getvar", data, opts);
    }

    // command "jobcmdexited" [call]
    JobCmdExitedCommand(client: DshClient, data: CommandJobCmdExitedData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "jobcmdexited", data, opts);
        return client.wshRpcCall("jobcmdexited", data, opts);
    }

    // command "jobcontrollerattachjob" [call]
    JobControllerAttachJobCommand(client: DshClient, data: CommandJobControllerAttachJobData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "jobcontrollerattachjob", data, opts);
        return client.wshRpcCall("jobcontrollerattachjob", data, opts);
    }

    // command "jobcontrollerconnectedjobs" [call]
    JobControllerConnectedJobsCommand(client: DshClient, opts?: RpcOpts): Promise<string[]> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "jobcontrollerconnectedjobs", null, opts);
        return client.wshRpcCall("jobcontrollerconnectedjobs", null, opts);
    }

    // command "jobcontrollerdeletejob" [call]
    JobControllerDeleteJobCommand(client: DshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "jobcontrollerdeletejob", data, opts);
        return client.wshRpcCall("jobcontrollerdeletejob", data, opts);
    }

    // command "jobcontrollerdetachjob" [call]
    JobControllerDetachJobCommand(client: DshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "jobcontrollerdetachjob", data, opts);
        return client.wshRpcCall("jobcontrollerdetachjob", data, opts);
    }

    // command "jobcontrollerdisconnectjob" [call]
    JobControllerDisconnectJobCommand(client: DshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "jobcontrollerdisconnectjob", data, opts);
        return client.wshRpcCall("jobcontrollerdisconnectjob", data, opts);
    }

    // command "jobcontrollerexitjob" [call]
    JobControllerExitJobCommand(client: DshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "jobcontrollerexitjob", data, opts);
        return client.wshRpcCall("jobcontrollerexitjob", data, opts);
    }

    // command "jobcontrollergetalljobmanagerstatus" [call]
    JobControllerGetAllJobManagerStatusCommand(client: DshClient, opts?: RpcOpts): Promise<JobManagerStatusUpdate[]> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "jobcontrollergetalljobmanagerstatus", null, opts);
        return client.wshRpcCall("jobcontrollergetalljobmanagerstatus", null, opts);
    }

    // command "jobcontrollerlist" [call]
    JobControllerListCommand(client: DshClient, opts?: RpcOpts): Promise<Job[]> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "jobcontrollerlist", null, opts);
        return client.wshRpcCall("jobcontrollerlist", null, opts);
    }

    // command "jobcontrollerreconnectjob" [call]
    JobControllerReconnectJobCommand(client: DshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "jobcontrollerreconnectjob", data, opts);
        return client.wshRpcCall("jobcontrollerreconnectjob", data, opts);
    }

    // command "jobcontrollerreconnectjobsforconn" [call]
    JobControllerReconnectJobsForConnCommand(client: DshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "jobcontrollerreconnectjobsforconn", data, opts);
        return client.wshRpcCall("jobcontrollerreconnectjobsforconn", data, opts);
    }

    // command "jobcontrollerstartjob" [call]
    JobControllerStartJobCommand(client: DshClient, data: CommandJobControllerStartJobData, opts?: RpcOpts): Promise<string> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "jobcontrollerstartjob", data, opts);
        return client.wshRpcCall("jobcontrollerstartjob", data, opts);
    }

    // command "jobinput" [call]
    JobInputCommand(client: DshClient, data: CommandJobInputData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "jobinput", data, opts);
        return client.wshRpcCall("jobinput", data, opts);
    }

    // command "jobprepareconnect" [call]
    JobPrepareConnectCommand(client: DshClient, data: CommandJobPrepareConnectData, opts?: RpcOpts): Promise<CommandJobConnectRtnData> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "jobprepareconnect", data, opts);
        return client.wshRpcCall("jobprepareconnect", data, opts);
    }

    // command "jobstartstream" [call]
    JobStartStreamCommand(client: DshClient, data: CommandJobStartStreamData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "jobstartstream", data, opts);
        return client.wshRpcCall("jobstartstream", data, opts);
    }

    // command "macosversion" [call]
    MacOSVersionCommand(client: DshClient, opts?: RpcOpts): Promise<string> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "macosversion", null, opts);
        return client.wshRpcCall("macosversion", null, opts);
    }

    // command "message" [call]
    MessageCommand(client: DshClient, data: CommandMessageData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "message", data, opts);
        return client.wshRpcCall("message", data, opts);
    }

    // command "networkonline" [call]
    NetworkOnlineCommand(client: DshClient, opts?: RpcOpts): Promise<boolean> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "networkonline", null, opts);
        return client.wshRpcCall("networkonline", null, opts);
    }

    // command "notify" [call]
    NotifyCommand(client: DshClient, data: DoraNotificationOptions, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "notify", data, opts);
        return client.wshRpcCall("notify", data, opts);
    }

    // command "path" [call]
    PathCommand(client: DshClient, data: PathCommandData, opts?: RpcOpts): Promise<string> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "path", data, opts);
        return client.wshRpcCall("path", data, opts);
    }

    // command "remotedisconnectfromjobmanager" [call]
    RemoteDisconnectFromJobManagerCommand(client: DshClient, data: CommandRemoteDisconnectFromJobManagerData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "remotedisconnectfromjobmanager", data, opts);
        return client.wshRpcCall("remotedisconnectfromjobmanager", data, opts);
    }

    // command "remotefilecopy" [call]
    RemoteFileCopyCommand(client: DshClient, data: CommandFileCopyData, opts?: RpcOpts): Promise<boolean> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "remotefilecopy", data, opts);
        return client.wshRpcCall("remotefilecopy", data, opts);
    }

    // command "remotefiledelete" [call]
    RemoteFileDeleteCommand(client: DshClient, data: CommandDeleteFileData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "remotefiledelete", data, opts);
        return client.wshRpcCall("remotefiledelete", data, opts);
    }

    // command "remotefileinfo" [call]
    RemoteFileInfoCommand(client: DshClient, data: string, opts?: RpcOpts): Promise<FileInfo> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "remotefileinfo", data, opts);
        return client.wshRpcCall("remotefileinfo", data, opts);
    }

    // command "remotefilejoin" [call]
    RemoteFileJoinCommand(client: DshClient, data: string[], opts?: RpcOpts): Promise<FileInfo> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "remotefilejoin", data, opts);
        return client.wshRpcCall("remotefilejoin", data, opts);
    }

    // command "remotefilemove" [call]
    RemoteFileMoveCommand(client: DshClient, data: CommandFileCopyData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "remotefilemove", data, opts);
        return client.wshRpcCall("remotefilemove", data, opts);
    }

    // command "remotefilemultiinfo" [call]
    RemoteFileMultiInfoCommand(client: DshClient, data: CommandRemoteFileMultiInfoData, opts?: RpcOpts): Promise<{[key: string]: FileInfo}> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "remotefilemultiinfo", data, opts);
        return client.wshRpcCall("remotefilemultiinfo", data, opts);
    }

    // command "remotefilestream" [call]
    RemoteFileStreamCommand(client: DshClient, data: CommandRemoteFileStreamData, opts?: RpcOpts): Promise<FileInfo> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "remotefilestream", data, opts);
        return client.wshRpcCall("remotefilestream", data, opts);
    }

    // command "remotefiletouch" [call]
    RemoteFileTouchCommand(client: DshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "remotefiletouch", data, opts);
        return client.wshRpcCall("remotefiletouch", data, opts);
    }

    // command "remotegetinfo" [call]
    RemoteGetInfoCommand(client: DshClient, opts?: RpcOpts): Promise<RemoteInfo> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "remotegetinfo", null, opts);
        return client.wshRpcCall("remotegetinfo", null, opts);
    }

    // command "remoteinstallrcfiles" [call]
    RemoteInstallRcFilesCommand(client: DshClient, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "remoteinstallrcfiles", null, opts);
        return client.wshRpcCall("remoteinstallrcfiles", null, opts);
    }

    // command "remotelistentries" [responsestream]
	RemoteListEntriesCommand(client: DshClient, data: CommandRemoteListEntriesData, opts?: RpcOpts): AsyncGenerator<CommandRemoteListEntriesRtnData, void, boolean> {
        if (this.mockClient) return this.mockClient.mockDshRpcStream(client, "remotelistentries", data, opts);
        return client.wshRpcStream("remotelistentries", data, opts);
    }

    // command "remotemkdir" [call]
    RemoteMkdirCommand(client: DshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "remotemkdir", data, opts);
        return client.wshRpcCall("remotemkdir", data, opts);
    }

    // command "remoteprocesslist" [call]
    RemoteProcessListCommand(client: DshClient, data: CommandRemoteProcessListData, opts?: RpcOpts): Promise<ProcessListResponse> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "remoteprocesslist", data, opts);
        return client.wshRpcCall("remoteprocesslist", data, opts);
    }

    // command "remoteprocesssignal" [call]
    RemoteProcessSignalCommand(client: DshClient, data: CommandRemoteProcessSignalData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "remoteprocesssignal", data, opts);
        return client.wshRpcCall("remoteprocesssignal", data, opts);
    }

    // command "remotereconnecttojobmanager" [call]
    RemoteReconnectToJobManagerCommand(client: DshClient, data: CommandRemoteReconnectToJobManagerData, opts?: RpcOpts): Promise<CommandRemoteReconnectToJobManagerRtnData> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "remotereconnecttojobmanager", data, opts);
        return client.wshRpcCall("remotereconnecttojobmanager", data, opts);
    }

    // command "remotestartjob" [call]
    RemoteStartJobCommand(client: DshClient, data: CommandRemoteStartJobData, opts?: RpcOpts): Promise<CommandStartJobRtnData> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "remotestartjob", data, opts);
        return client.wshRpcCall("remotestartjob", data, opts);
    }

    // command "remotestreamcpudata" [responsestream]
	RemoteStreamCpuDataCommand(client: DshClient, opts?: RpcOpts): AsyncGenerator<TimeSeriesData, void, boolean> {
        if (this.mockClient) return this.mockClient.mockDshRpcStream(client, "remotestreamcpudata", null, opts);
        return client.wshRpcStream("remotestreamcpudata", null, opts);
    }

    // command "remoteterminatejobmanager" [call]
    RemoteTerminateJobManagerCommand(client: DshClient, data: CommandRemoteTerminateJobManagerData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "remoteterminatejobmanager", data, opts);
        return client.wshRpcCall("remoteterminatejobmanager", data, opts);
    }

    // command "remotewritefile" [call]
    RemoteWriteFileCommand(client: DshClient, data: FileData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "remotewritefile", data, opts);
        return client.wshRpcCall("remotewritefile", data, opts);
    }

    // command "resolveids" [call]
    ResolveIdsCommand(client: DshClient, data: CommandResolveIdsData, opts?: RpcOpts): Promise<CommandResolveIdsRtnData> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "resolveids", data, opts);
        return client.wshRpcCall("resolveids", data, opts);
    }

    // command "routeannounce" [call]
    RouteAnnounceCommand(client: DshClient, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "routeannounce", null, opts);
        return client.wshRpcCall("routeannounce", null, opts);
    }

    // command "routeunannounce" [call]
    RouteUnannounceCommand(client: DshClient, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "routeunannounce", null, opts);
        return client.wshRpcCall("routeunannounce", null, opts);
    }

    // command "setblockfocus" [call]
    SetBlockFocusCommand(client: DshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "setblockfocus", data, opts);
        return client.wshRpcCall("setblockfocus", data, opts);
    }

    // command "setconfig" [call]
    SetConfigCommand(client: DshClient, data: SettingsType, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "setconfig", data, opts);
        return client.wshRpcCall("setconfig", data, opts);
    }

    // command "setmeta" [call]
    SetMetaCommand(client: DshClient, data: CommandSetMetaData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "setmeta", data, opts);
        return client.wshRpcCall("setmeta", data, opts);
    }

    // command "setpeerinfo" [call]
    SetPeerInfoCommand(client: DshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "setpeerinfo", data, opts);
        return client.wshRpcCall("setpeerinfo", data, opts);
    }

    // command "setrtinfo" [call]
    SetRTInfoCommand(client: DshClient, data: CommandSetRTInfoData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "setrtinfo", data, opts);
        return client.wshRpcCall("setrtinfo", data, opts);
    }

    // command "setsecrets" [call]
    SetSecretsCommand(client: DshClient, data: {[key: string]: string}, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "setsecrets", data, opts);
        return client.wshRpcCall("setsecrets", data, opts);
    }

    // command "setvar" [call]
    SetVarCommand(client: DshClient, data: CommandVarData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "setvar", data, opts);
        return client.wshRpcCall("setvar", data, opts);
    }

    // command "startjob" [call]
    StartJobCommand(client: DshClient, data: CommandStartJobData, opts?: RpcOpts): Promise<CommandStartJobRtnData> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "startjob", data, opts);
        return client.wshRpcCall("startjob", data, opts);
    }

    // command "streamcpudata" [responsestream]
	StreamCpuDataCommand(client: DshClient, data: CpuDataRequest, opts?: RpcOpts): AsyncGenerator<TimeSeriesData, void, boolean> {
        if (this.mockClient) return this.mockClient.mockDshRpcStream(client, "streamcpudata", data, opts);
        return client.wshRpcStream("streamcpudata", data, opts);
    }

    // command "streamdata" [call]
    StreamDataCommand(client: DshClient, data: CommandStreamData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "streamdata", data, opts);
        return client.wshRpcCall("streamdata", data, opts);
    }

    // command "streamdataack" [call]
    StreamDataAckCommand(client: DshClient, data: CommandStreamAckData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "streamdataack", data, opts);
        return client.wshRpcCall("streamdataack", data, opts);
    }

    // command "streamtest" [responsestream]
	StreamTestCommand(client: DshClient, opts?: RpcOpts): AsyncGenerator<number, void, boolean> {
        if (this.mockClient) return this.mockClient.mockDshRpcStream(client, "streamtest", null, opts);
        return client.wshRpcStream("streamtest", null, opts);
    }

    // command "termgetscrollbacklines" [call]
    TermGetScrollbackLinesCommand(client: DshClient, data: CommandTermGetScrollbackLinesData, opts?: RpcOpts): Promise<CommandTermGetScrollbackLinesRtnData> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "termgetscrollbacklines", data, opts);
        return client.wshRpcCall("termgetscrollbacklines", data, opts);
    }

    // command "test" [call]
    TestCommand(client: DshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "test", data, opts);
        return client.wshRpcCall("test", data, opts);
    }

    // command "testmultiarg" [call]
    TestMultiArgCommand(client: DshClient, arg1: string, arg2: number, arg3: boolean, opts?: RpcOpts): Promise<string> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "testmultiarg", { args: [arg1, arg2, arg3] }, opts);
        return client.wshRpcCall("testmultiarg", { args: [arg1, arg2, arg3] }, opts);
    }

    // command "updatetabname" [call]
    UpdateTabNameCommand(client: DshClient, arg1: string, arg2: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "updatetabname", { args: [arg1, arg2] }, opts);
        return client.wshRpcCall("updatetabname", { args: [arg1, arg2] }, opts);
    }

    // command "updateworkspacetabids" [call]
    UpdateWorkspaceTabIdsCommand(client: DshClient, arg1: string, arg2: string[], opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "updateworkspacetabids", { args: [arg1, arg2] }, opts);
        return client.wshRpcCall("updateworkspacetabids", { args: [arg1, arg2] }, opts);
    }

    // command "waitforroute" [call]
    WaitForRouteCommand(client: DshClient, data: CommandWaitForRouteData, opts?: RpcOpts): Promise<boolean> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "waitforroute", data, opts);
        return client.wshRpcCall("waitforroute", data, opts);
    }

    // command "webselector" [call]
    WebSelectorCommand(client: DshClient, data: CommandWebSelectorData, opts?: RpcOpts): Promise<string[]> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "webselector", data, opts);
        return client.wshRpcCall("webselector", data, opts);
    }

    // command "workspacelist" [call]
    WorkspaceListCommand(client: DshClient, opts?: RpcOpts): Promise<WorkspaceInfoData[]> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "workspacelist", null, opts);
        return client.wshRpcCall("workspacelist", null, opts);
    }

    // command "writetempfile" [call]
    WriteTempFileCommand(client: DshClient, data: CommandWriteTempFileData, opts?: RpcOpts): Promise<string> {
        if (this.mockClient) return this.mockClient.mockDshRpcCall(client, "writetempfile", data, opts);
        return client.wshRpcCall("writetempfile", data, opts);
    }

}

export const RpcApi = new RpcApiType();
