// Copyright 2026, Command Line Inc.
// SPDX-License-Identifier: Apache-2.0

// generated by cmd/generate/main-generatets.go

import * as WOS from "./wos";
import type { DoraEnv } from "@/app/doraenv/doraenv";

function callBackendService(doraEnv: DoraEnv, service: string, method: string, args: any[], noUIContext?: boolean): Promise<any> {
    if (doraEnv != null) {
        return doraEnv.callBackendService(service, method, args, noUIContext)
    }
    return WOS.callBackendService(service, method, args, noUIContext);
}

// blockservice.BlockService (block)
export class BlockServiceType {
    doraEnv: DoraEnv;

    constructor(doraEnv?: DoraEnv) {
        this.doraEnv = doraEnv;
    }

    // queue a layout action to cleanup orphaned blocks in the tab
    // @returns object updates
    CleanupOrphanedBlocks(tabId: string): Promise<void> {
        return callBackendService(this?.doraEnv, "block", "CleanupOrphanedBlocks", Array.from(arguments))
    }
    GetControllerStatus(arg2: string): Promise<BlockControllerRuntimeStatus> {
        return callBackendService(this?.doraEnv, "block", "GetControllerStatus", Array.from(arguments))
    }

    // save the terminal state to a blockfile
    SaveTerminalState(blockId: string, state: string, stateType: string, ptyOffset: number, termSize: TermSize): Promise<void> {
        return callBackendService(this?.doraEnv, "block", "SaveTerminalState", Array.from(arguments))
    }
}

export const BlockService = new BlockServiceType();

// clientservice.ClientService (client)
export class ClientServiceType {
    doraEnv: DoraEnv;

    constructor(doraEnv?: DoraEnv) {
        this.doraEnv = doraEnv;
    }

    FocusWindow(arg2: string): Promise<void> {
        return callBackendService(this?.doraEnv, "client", "FocusWindow", Array.from(arguments))
    }
    GetClientData(): Promise<Client> {
        return callBackendService(this?.doraEnv, "client", "GetClientData", Array.from(arguments))
    }
    GetTab(arg1: string): Promise<Tab> {
        return callBackendService(this?.doraEnv, "client", "GetTab", Array.from(arguments))
    }
    TelemetryUpdate(arg2: boolean): Promise<void> {
        return callBackendService(this?.doraEnv, "client", "TelemetryUpdate", Array.from(arguments))
    }
}

export const ClientService = new ClientServiceType();

// objectservice.ObjectService (object)
export class ObjectServiceType {
    doraEnv: DoraEnv;

    constructor(doraEnv?: DoraEnv) {
        this.doraEnv = doraEnv;
    }

    // @returns blockId (and object updates)
    CreateBlock(blockDef: BlockDef, rtOpts: RuntimeOpts): Promise<string> {
        return callBackendService(this?.doraEnv, "object", "CreateBlock", Array.from(arguments))
    }

    // @returns object updates
    DeleteBlock(blockId: string): Promise<void> {
        return callBackendService(this?.doraEnv, "object", "DeleteBlock", Array.from(arguments))
    }

    // get dora object by oref
    GetObject(oref: string): Promise<DoraObj> {
        return callBackendService(this?.doraEnv, "object", "GetObject", Array.from(arguments))
    }

    // @returns objects
    GetObjects(orefs: string[]): Promise<DoraObj[]> {
        return callBackendService(this?.doraEnv, "object", "GetObjects", Array.from(arguments))
    }

    // @returns object updates
    UpdateObject(doraObj: DoraObj, returnUpdates: boolean): Promise<void> {
        return callBackendService(this?.doraEnv, "object", "UpdateObject", Array.from(arguments))
    }

    // @returns object updates
    UpdateObjectMeta(oref: string, meta: MetaType): Promise<void> {
        return callBackendService(this?.doraEnv, "object", "UpdateObjectMeta", Array.from(arguments))
    }
}

export const ObjectService = new ObjectServiceType();

// userinputservice.UserInputService (userinput)
export class UserInputServiceType {
    doraEnv: DoraEnv;

    constructor(doraEnv?: DoraEnv) {
        this.doraEnv = doraEnv;
    }

    SendUserInputResponse(arg1: UserInputResponse): Promise<void> {
        return callBackendService(this?.doraEnv, "userinput", "SendUserInputResponse", Array.from(arguments))
    }
}

export const UserInputService = new UserInputServiceType();

// windowservice.WindowService (window)
export class WindowServiceType {
    doraEnv: DoraEnv;

    constructor(doraEnv?: DoraEnv) {
        this.doraEnv = doraEnv;
    }

    CloseWindow(windowId: string, fromElectron: boolean): Promise<void> {
        return callBackendService(this?.doraEnv, "window", "CloseWindow", Array.from(arguments))
    }
    CreateWindow(winSize: WinSize, workspaceId: string): Promise<DoraWindow> {
        return callBackendService(this?.doraEnv, "window", "CreateWindow", Array.from(arguments))
    }
    GetWindow(windowId: string): Promise<DoraWindow> {
        return callBackendService(this?.doraEnv, "window", "GetWindow", Array.from(arguments))
    }

    // set window position and size
    // @returns object updates
    SetWindowPosAndSize(windowId: string, pos: Point, size: WinSize): Promise<void> {
        return callBackendService(this?.doraEnv, "window", "SetWindowPosAndSize", Array.from(arguments))
    }
    SwitchWorkspace(windowId: string, workspaceId: string): Promise<Workspace> {
        return callBackendService(this?.doraEnv, "window", "SwitchWorkspace", Array.from(arguments))
    }
}

export const WindowService = new WindowServiceType();

// workspaceservice.WorkspaceService (workspace)
export class WorkspaceServiceType {
    doraEnv: DoraEnv;

    constructor(doraEnv?: DoraEnv) {
        this.doraEnv = doraEnv;
    }

    // @returns CloseTabRtn (and object updates)
    CloseTab(workspaceId: string, tabId: string, fromElectron: boolean): Promise<CloseTabRtnType> {
        return callBackendService(this?.doraEnv, "workspace", "CloseTab", Array.from(arguments))
    }

    // @returns tabId (and object updates)
    CreateTab(workspaceId: string, tabName: string, activateTab: boolean): Promise<string> {
        return callBackendService(this?.doraEnv, "workspace", "CreateTab", Array.from(arguments))
    }

    // @returns workspaceId
    CreateWorkspace(name: string, icon: string, color: string, applyDefaults: boolean): Promise<string> {
        return callBackendService(this?.doraEnv, "workspace", "CreateWorkspace", Array.from(arguments))
    }

    // @returns object updates
    DeleteWorkspace(workspaceId: string): Promise<string> {
        return callBackendService(this?.doraEnv, "workspace", "DeleteWorkspace", Array.from(arguments))
    }

    // @returns colors
    GetColors(): Promise<string[]> {
        return callBackendService(this?.doraEnv, "workspace", "GetColors", Array.from(arguments))
    }

    // @returns icons
    GetIcons(): Promise<string[]> {
        return callBackendService(this?.doraEnv, "workspace", "GetIcons", Array.from(arguments))
    }

    // @returns workspace
    GetWorkspace(workspaceId: string): Promise<Workspace> {
        return callBackendService(this?.doraEnv, "workspace", "GetWorkspace", Array.from(arguments))
    }
    ListWorkspaces(): Promise<WorkspaceListEntry[]> {
        return callBackendService(this?.doraEnv, "workspace", "ListWorkspaces", Array.from(arguments))
    }

    // @returns object updates
    SetActiveTab(workspaceId: string, tabId: string): Promise<void> {
        return callBackendService(this?.doraEnv, "workspace", "SetActiveTab", Array.from(arguments))
    }

    // @returns object updates
    UpdateWorkspace(workspaceId: string, name: string, icon: string, color: string, applyDefaults: boolean): Promise<void> {
        return callBackendService(this?.doraEnv, "workspace", "UpdateWorkspace", Array.from(arguments))
    }
}

export const WorkspaceService = new WorkspaceServiceType();

export const AllServiceTypes = {
    "block": BlockServiceType,
    "client": ClientServiceType,
    "object": ObjectServiceType,
    "userinput": UserInputServiceType,
    "window": WindowServiceType,
    "workspace": WorkspaceServiceType,
};

export const AllServiceImpls = {
    "block": BlockService,
    "client": ClientService,
    "object": ObjectService,
    "userinput": UserInputService,
    "window": WindowService,
    "workspace": WorkspaceService,
};
